#!/usr/bin/env bash
# SSH client configuration must be configured to refuse to authenticate using a password
# SSH client configuration must be configured to use the private key ~/.ssh/school

Host 3.90.85.133
	user ubuntu
	IdentifyFile ~/.ssh/school
	PasswordAuthentication no
